import slugify from '../utils/slugify'

export default {
  title: 'Pages',
  name: 'pages',
  type: 'document',
  __experimental_actions: ['update', 'create', 'delete', 'publish'],
  fields: [
    {
      title: 'Title',
      name: 'title',
      type: 'string',
      validation: Rule => Rule.required()
    },
    // {
    //   title: "Content Sections",
    //   description: 'The modular content sections for this page, will auto-generate the menu at the top of the pange',
    //   name: "contentSections",
    //   type: 'array',
    //   of: [
    //     {
    //       type: 'object',
    //       title: 'Item',
    //       name: "item",
    //       fields: [
    //         {
    //           title: "Title",
    //           name: "title",
    //           type: "string"
    //         },
    //         {
    //           title: "Content Blocks",
    //           description: 'The modular content blocks for this page',
    //           name: "contentBlocks",
    //           type: 'array',
    //           of: [
                
    //             {type: 'textBlock', title: 'Text'},
    //             {type: 'headingBlock', title: 'Text Heading'},
    //             {type: 'imageBlock', title: 'Full Width Image'},
    //             {type: 'imageGridBlock', title: 'Image Grid'},
    //             {type: 'blockquoteBlock', title: 'Quote'},
    //             {type: 'embedBlock', title: 'Embed (Vimeo etc.)'},
    //             {type: 'codeBlock', title: 'Code'},
    //             {type: 'listBlock', title: 'List'}
    //           ]
    //         },
    //       ],
    //       preview: {
    //         select: {
    //           title: 'title',
    //         },
    //         prepare ({ title }) {
    //           return {
    //             title: title,
    //           }
    //         }
    //       },
    //     },
    //   ]
    // },
    {
      title: "Content Blocks",
      description: 'The modular content blocks for this page',
      name: "contentBlocks",
      type: 'array',
      of: [
        {type: 'jumpNavSectionBlock', title: 'Jump Nav Section Block'},
        {type: 'textBlock', title: 'Text'},
        {type: 'headingBlock', title: 'Text Heading'},
        {type: 'imageBlock', title: 'Full Width Image'},
        {type: 'imageGridBlock', title: 'Image Grid'},
        {type: 'blockquoteBlock', title: 'Quote'},
        {type: 'embedBlock', title: 'Embed (Vimeo etc.)'},
        {type: 'embedTypeformBlock', title: 'Embed (Typeform)'},
        {type: 'codeBlock', title: 'Code'},
        {type: 'listBlock', title: 'List'}
      ]
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = ''
          let campaignSlug = ''
          if (doc.title) {
            titleSlug = `${doc.title}`
          } else {
            titleSlug = ''
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`
          } else {
            campaignSlug = ''
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title'
    },
    prepare ({ title }) {
      return {
        title
      }
    }
  }
}